[package]
name = "megaminx"
version = "0.2.5"
edition = "2021"
authors = ["genr8eofl <genBTC@gmx.com>"]

[dependencies.sdl2]
version = "0.37"
features = ["gfx"]

[dependencies]
gl = "0.14.0"
glium = "0.36.0"
glm = "0.2.3"
