[package]
name = "megaminx"
version = "0.2.0"
edition = "2021"
authors = ["genr8eofl <genBTC@gmx.com>"]

[dependencies.sdl2]
version = "0.36"
features = ["gfx"]

[dependencies]
gl = "0.14.0"
glium = "0.34.0"
